name: {{ cookiecutter.repo_name }}
channels:
  - conda-forge
  - default
dependencies:
  - python={{ cookiecutter.python_version }}
  - pip
  - numpy=1.21.1
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - ipykernel
  - h5py
  - tqdm
  - seaborn
  - numexpr
  - obspy
  {% if cookiecutter.install_dev == 'y' %}
  - isort
  - black
  - flake8
  {% endif %}
