name: {{ cookiecutter.repo_name }}
channels:
  - conda-forge
  - default
dependencies:
  - python={{ cookiecutter.python_version }}
  {% if cookiecutter.use_mlflow == 'y' %}
  - mlflow
  {% endif %}
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - jupyter
  - jupyterlab
  - h5py
  - tqdm
  - seaborn
  - numexpr
  - obspy
  - 
  {% if cookiecutter.install_dev == 'y' %}
  - isort
  - black
  - flake8
  {% endif %}
