name: {{ cookiecutter.repo_name }}
channels:
  - conda-forge
  - default
dependencies:
  - python=3.9
  - pip
  - numpy=1.21.1
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - ipykernel
  - h5py
  - tqdm
  - seaborn
  - numexpr
  - obspy
